#!/bin/bash

PDIR="#PROJECTDIR#"
RUNID="gwGMDms"
NP=32

YMD=`date +%Y-%m-%d`

cd $PDIR
qsub qsubmit_MAAT_arg.pbs -N "${YMD}_MAAT_${RUNID}_PSA" -v ARGS="runid<-'${RUNID}' multic<-T procs<-${NP} factorial<-F uq<-T mod_out<-'slim' procSA<-T salt<-F psa_n<-1000 eval_strings<-T" 
qsub qsubmit_MAAT_arg.pbs -N "${YMD}_MAAT_${RUNID}_SSA" -v ARGS="runid<-'${RUNID}' multic<-T procs<-${NP} factorial<-F uq<-T mod_out<-'slim' procSA<-F salt<-T psa_n<-1000 sobol_nmult<-1000 eval_strings<-T" 
