#!/bin/bash

# simple bash script to copy MAAT runfile to a project directory
# takes the full path of the project directory as an argument

NMOD=$1
run_scripts=${2-$PWD/run_scripts}
src=${3-$PWD/src}

mkdir -p $src/$NMOD >/dev/null 2>&1
cp       $src/template/* $src/$NMOD && chmod 755 $src/$NMOD/*
rename   "s/template/${NMOD}/g" $src/$NMOD/*

# if else
if [[ $OSTYPE == darwin* ]]; then
  sed -i '' "s@template@$NMOD@g"  $src/$NMOD/*
else
  sed -i    "s@template@$NMOD@g"  $src/$NMOD/*
fi
